### ISSUE TITLE
aria role and fallback text

### ISSUE THREAD

**Issue by peterblazejewicz** [gschier/html-share-buttons#1]
@gschier Gregory, can version with fallback text and for screen readers be added? Here is how relevant section of blog looks in Lynx browser (look, no links, only big yellow horizontal rule).
![screen shot 2014-11-15 at 21 17 27](https://cloud.githubusercontent.com/assets/14539/5059066/6e3230ce-6d0d-11e4-928d-16f377efda2e.png)
http://www.filamentgroup.com/lab/bulletproof_icon_fonts.html
similar topic on Shopify:  https://github.com/Shopify/Timber/pull/80#discussion_r13349977 (they were cooking bullet proof theme for their customers).
In Bootstrap 3.\* semantics:

``` html
<!-- Twitter -->
<a href="http://twitter.com/share?url=https://github.com/gschier/html-share-buttons&text=HMTL%20Share%20Buttons&via=GregorySchier" target="_blank" class="share-btn twitter">
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter</span>
</a>
```

![screen shot 2014-11-15 at 21 25 28](https://cloud.githubusercontent.com/assets/14539/5059082/f5a105b2-6d0d-11e4-81aa-a422850a4728.png)

**Comment by gschier** [comment]
sorry @peterblazejewicz I must have missed this when you posted. I will update it so it looks good in Lynx.

Thanks for posting!

**Comment by peterblazejewicz** [comment]
@gschier to be clear: it is not just for a browser like Lynx, it's for providing textual context to links. One can see Twitter link - but can't read it.
Thanks!

**Comment by gschier** [comment]
Closing this as stale.
