### ISSUE TITLE
How to make link share to dinamis

### ISSUE THREAD

**Issue by sidaurukfreddy** [gschier/html-share-buttons#3]
Hi thanks for effort make this, how to make this share url to be dinamis, where is the code to change ! every time i make this share already share your blog, Thanks

**Comment by gschier** [comment]
Hey @sidaurukfreddy. To change what they share you just have to update the share url and text within each button link. Check out the attached blog post for details.

**Comment by sidaurukfreddy** [comment]
I didn't see detail for share dynamic url in your blog, you just blogged how to share with media social without more explanation only some sentences here

"Share links are very simple. Simply make an anchor tag that points to a sharing URL of the desired social network and attach some query params to tell the network what to share."

will big thanks for detail

Freddy Sidauruk

**Comment by gschier** [comment]
I know this is old but I wanted to provide an answer before closing this issue. The most common way to make your links dynamic is to fill in the dynamic parts using whatever your website's template language is. You can see an example on my blog here: 

https://github.com/gschier/schier.co/blob/602675cad4e81eb5127618275da6dbe37539748e/themes/hugo-schier-theme/layouts/blog/single.html#L49-L66
